# This workflow is triggered on push to the repository.
name: "Build PDF"
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: release
          tag_name: release
          token: ${{ secrets.GITHUB_TOKEN }}
          files: resume.pdf
          fail_on_unmatched_files: true
